version: '3.0'

services:
  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "6379:6379"

  sender:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: uv run main.py
    env_file:
      - ./.env
